"""
Indian States and Districts Data for eCourts Scraper
Contains fallback district data for all Indian states and union territories
Updated: October 2025
"""

FALLBACK_DISTRICTS = {
    '01': [  # Andhra Pradesh
        {'code': '01', 'name': 'Anantapur'},
        {'code': '02', 'name': 'Chittoor'},
        {'code': '03', 'name': 'East Godavari'},
        {'code': '04', 'name': 'Guntur'},
        {'code': '05', 'name': 'Kadapa'},
        {'code': '06', 'name': 'Krishna'},
        {'code': '07', 'name': 'Kurnool'},
        {'code': '08', 'name': 'Nellore'},
        {'code': '09', 'name': 'Prakasam'},
        {'code': '10', 'name': 'Srikakulam'},
        {'code': '11', 'name': 'Visakhapatnam'},
        {'code': '12', 'name': 'Vizianagaram'},
        {'code': '13', 'name': 'West Godavari'}
    ],
    '02': [  # Arunachal Pradesh
        {'code': '01', 'name': 'Tawang'},
        {'code': '02', 'name': 'West Kameng'},
        {'code': '03', 'name': 'East Kameng'},
        {'code': '04', 'name': 'Pakke-Kessang'},
        {'code': '05', 'name': 'Kurung Kumey'},
        {'code': '06', 'name': 'Papum Pare'},
        {'code': '07', 'name': 'Kra Daadi'},
        {'code': '08', 'name': 'Lower Subansiri'},
        {'code': '09', 'name': 'Kamle'},
        {'code': '10', 'name': 'Upper Subansiri'},
        {'code': '11', 'name': 'Shi-Yomi'},
        {'code': '12', 'name': 'West Siang'},
        {'code': '13', 'name': 'Siang'},
        {'code': '14', 'name': 'Lower Siang'},
        {'code': '15', 'name': 'Lepa-Rada'},
        {'code': '16', 'name': 'Upper Siang'},
        {'code': '17', 'name': 'East Siang'},
        {'code': '18', 'name': 'Dibang Valley'},
        {'code': '19', 'name': 'Lower Dibang Valley'},
        {'code': '20', 'name': 'Lohit'},
        {'code': '21', 'name': 'Anjaw'},
        {'code': '22', 'name': 'Namsai'},
        {'code': '23', 'name': 'Changlang'},
        {'code': '24', 'name': 'Tirap'},
        {'code': '25', 'name': 'Longding'},
        {'code': '26', 'name': 'Bichom'},
        {'code': '27', 'name': 'Keyi Panyor'}
    ],
    '03': [  # Assam
        {'code': '01', 'name': 'Baksa'},
        {'code': '02', 'name': 'Barpeta'},
        {'code': '03', 'name': 'Biswanath'},
        {'code': '04', 'name': 'Bongaigaon'},
        {'code': '05', 'name': 'Cachar'},
        {'code': '06', 'name': 'Charaideo'},
        {'code': '07', 'name': 'Chirang'},
        {'code': '08', 'name': 'Darrang'},
        {'code': '09', 'name': 'Dhemaji'},
        {'code': '10', 'name': 'Dhubri'},
        {'code': '11', 'name': 'Dibrugarh'},
        {'code': '12', 'name': 'Dima Hasao'},
        {'code': '13', 'name': 'Goalpara'},
        {'code': '14', 'name': 'Golaghat'},
        {'code': '15', 'name': 'Hailakandi'},
        {'code': '16', 'name': 'Hojai'},
        {'code': '17', 'name': 'Jorhat'},
        {'code': '18', 'name': 'Kamrup'},
        {'code': '19', 'name': 'Kamrup Metropolitan'},
        {'code': '20', 'name': 'Karbi Anglong'},
        {'code': '21', 'name': 'Karimganj'},
        {'code': '22', 'name': 'Kokrajhar'},
        {'code': '23', 'name': 'Lakhimpur'},
        {'code': '24', 'name': 'Majuli'},
        {'code': '25', 'name': 'Morigaon'},
        {'code': '26', 'name': 'Nagaon'},
        {'code': '27', 'name': 'Nalbari'},
        {'code': '28', 'name': 'Sivasagar'},
        {'code': '29', 'name': 'Sonitpur'},
        {'code': '30', 'name': 'South Salmara Mankachar'},
        {'code': '31', 'name': 'Tinsukia'},
        {'code': '32', 'name': 'Udalguri'},
        {'code': '33', 'name': 'West Karbi Anglong'}
    ],
    '04': [  # Bihar
        {'code': '01', 'name': 'Araria'},
        {'code': '02', 'name': 'Arwal'},
        {'code': '03', 'name': 'Aurangabad'},
        {'code': '04', 'name': 'Banka'},
        {'code': '05', 'name': 'Begusarai'},
        {'code': '06', 'name': 'Bhagalpur'},
        {'code': '07', 'name': 'Bhojpur'},
        {'code': '08', 'name': 'Buxar'},
        {'code': '09', 'name': 'Darbhanga'},
        {'code': '10', 'name': 'East Champaran'},
        {'code': '11', 'name': 'Gaya'},
        {'code': '12', 'name': 'Gopalganj'},
        {'code': '13', 'name': 'Jamui'},
        {'code': '14', 'name': 'Jehanabad'},
        {'code': '15', 'name': 'Kaimur'},
        {'code': '16', 'name': 'Katihar'},
        {'code': '17', 'name': 'Khagaria'},
        {'code': '18', 'name': 'Kishanganj'},
        {'code': '19', 'name': 'Lakhisarai'},
        {'code': '20', 'name': 'Madhepura'},
        {'code': '21', 'name': 'Madhubani'},
        {'code': '22', 'name': 'Munger'},
        {'code': '23', 'name': 'Muzaffarpur'},
        {'code': '24', 'name': 'Nalanda'},
        {'code': '25', 'name': 'Nawada'},
        {'code': '26', 'name': 'Patna'},
        {'code': '27', 'name': 'Purnia'},
        {'code': '28', 'name': 'Rohtas'},
        {'code': '29', 'name': 'Saharsa'},
        {'code': '30', 'name': 'Samastipur'},
        {'code': '31', 'name': 'Saran'},
        {'code': '32', 'name': 'Sheikhpura'},
        {'code': '33', 'name': 'Sheohar'},
        {'code': '34', 'name': 'Sitamarhi'},
        {'code': '35', 'name': 'Siwan'},
        {'code': '36', 'name': 'Supaul'},
        {'code': '37', 'name': 'Vaishali'},
        {'code': '38', 'name': 'West Champaran'}
    ],
    '05': [  # Chhattisgarh
        {'code': '01', 'name': 'Balod'},
        {'code': '02', 'name': 'Baloda Bazar'},
        {'code': '03', 'name': 'Balrampur'},
        {'code': '04', 'name': 'Bastar'},
        {'code': '05', 'name': 'Bemetara'},
        {'code': '06', 'name': 'Bijapur'},
        {'code': '07', 'name': 'Bilaspur'},
        {'code': '08', 'name': 'Dantewada'},
        {'code': '09', 'name': 'Dhamtari'},
        {'code': '10', 'name': 'Durg'},
        {'code': '11', 'name': 'Gariaband'},
        {'code': '12', 'name': 'Janjgir-Champa'},
        {'code': '13', 'name': 'Jashpur'},
        {'code': '14', 'name': 'Kabirdham'},
        {'code': '15', 'name': 'Kanker'},
        {'code': '16', 'name': 'Kondagaon'},
        {'code': '17', 'name': 'Korba'},
        {'code': '18', 'name': 'Korea'},
        {'code': '19', 'name': 'Mahasamund'},
        {'code': '20', 'name': 'Mungeli'},
        {'code': '21', 'name': 'Narayanpur'},
        {'code': '22', 'name': 'Raigarh'},
        {'code': '23', 'name': 'Raipur'},
        {'code': '24', 'name': 'Rajnandgaon'},
        {'code': '25', 'name': 'Sukma'},
        {'code': '26', 'name': 'Surajpur'},
        {'code': '27', 'name': 'Surguja'}
    ],
    '06': [  # Goa
        {'code': '01', 'name': 'North Goa'},
        {'code': '02', 'name': 'South Goa'}
    ],
    '07': [  # Delhi
        {'code': '01', 'name': 'Central Delhi'},
        {'code': '02', 'name': 'East Delhi'},
        {'code': '03', 'name': 'New Delhi'},
        {'code': '04', 'name': 'North Delhi'},
        {'code': '05', 'name': 'North East Delhi'},
        {'code': '06', 'name': 'North West Delhi'},
        {'code': '07', 'name': 'Shahdara'},
        {'code': '08', 'name': 'South Delhi'},
        {'code': '09', 'name': 'South East Delhi'},
        {'code': '10', 'name': 'South West Delhi'},
        {'code': '11', 'name': 'West Delhi'}
    ],
    '08': [  # Gujarat
        {'code': '01', 'name': 'Ahmedabad'},
        {'code': '02', 'name': 'Amreli'},
        {'code': '03', 'name': 'Anand'},
        {'code': '04', 'name': 'Aravalli'},
        {'code': '05', 'name': 'Banaskantha'},
        {'code': '06', 'name': 'Bharuch'},
        {'code': '07', 'name': 'Bhavnagar'},
        {'code': '08', 'name': 'Botad'},
        {'code': '09', 'name': 'Chhota Udaipur'},
        {'code': '10', 'name': 'Dahod'},
        {'code': '11', 'name': 'Dang'},
        {'code': '12', 'name': 'Devbhoomi Dwarka'},
        {'code': '13', 'name': 'Gandhinagar'},
        {'code': '14', 'name': 'Gir Somnath'},
        {'code': '15', 'name': 'Jamnagar'},
        {'code': '16', 'name': 'Junagadh'},
        {'code': '17', 'name': 'Kheda'},
        {'code': '18', 'name': 'Kutch'},
        {'code': '19', 'name': 'Mahisagar'},
        {'code': '20', 'name': 'Mehsana'},
        {'code': '21', 'name': 'Morbi'},
        {'code': '22', 'name': 'Narmada'},
        {'code': '23', 'name': 'Navsari'},
        {'code': '24', 'name': 'Panchmahal'},
        {'code': '25', 'name': 'Patan'},
        {'code': '26', 'name': 'Porbandar'},
        {'code': '27', 'name': 'Rajkot'},
        {'code': '28', 'name': 'Sabarkantha'},
        {'code': '29', 'name': 'Surat'},
        {'code': '30', 'name': 'Surendranagar'},
        {'code': '31', 'name': 'Tapi'},
        {'code': '32', 'name': 'Vadodara'},
        {'code': '33', 'name': 'Valsad'}
    ],
    '09': [  # Haryana
        {'code': '01', 'name': 'Ambala'},
        {'code': '02', 'name': 'Bhiwani'},
        {'code': '03', 'name': 'Charkhi Dadri'},
        {'code': '04', 'name': 'Faridabad'},
        {'code': '05', 'name': 'Fatehabad'},
        {'code': '06', 'name': 'Gurugram'},
        {'code': '07', 'name': 'Hisar'},
        {'code': '08', 'name': 'Jhajjar'},
        {'code': '09', 'name': 'Jind'},
        {'code': '10', 'name': 'Kaithal'},
        {'code': '11', 'name': 'Karnal'},
        {'code': '12', 'name': 'Kurukshetra'},
        {'code': '13', 'name': 'Mahendragarh'},
        {'code': '14', 'name': 'Nuh'},
        {'code': '15', 'name': 'Palwal'},
        {'code': '16', 'name': 'Panchkula'},
        {'code': '17', 'name': 'Panipat'},
        {'code': '18', 'name': 'Rewari'},
        {'code': '19', 'name': 'Rohtak'},
        {'code': '20', 'name': 'Sirsa'},
        {'code': '21', 'name': 'Sonipat'},
        {'code': '22', 'name': 'Yamunanagar'}
    ],
    '10': [  # Himachal Pradesh
        {'code': '01', 'name': 'Bilaspur'},
        {'code': '02', 'name': 'Chamba'},
        {'code': '03', 'name': 'Hamirpur'},
        {'code': '04', 'name': 'Kangra'},
        {'code': '05', 'name': 'Kinnaur'},
        {'code': '06', 'name': 'Kullu'},
        {'code': '07', 'name': 'Lahaul and Spiti'},
        {'code': '08', 'name': 'Mandi'},
        {'code': '09', 'name': 'Shimla'},
        {'code': '10', 'name': 'Sirmaur'},
        {'code': '11', 'name': 'Solan'},
        {'code': '12', 'name': 'Una'}
    ],
    '11': [  # Jammu and Kashmir
        {'code': '01', 'name': 'Anantnag'},
        {'code': '02', 'name': 'Bandipora'},
        {'code': '03', 'name': 'Baramulla'},
        {'code': '04', 'name': 'Budgam'},
        {'code': '05', 'name': 'Doda'},
        {'code': '06', 'name': 'Ganderbal'},
        {'code': '07', 'name': 'Jammu'},
        {'code': '08', 'name': 'Kathua'},
        {'code': '09', 'name': 'Kishtwar'},
        {'code': '10', 'name': 'Kulgam'},
        {'code': '11', 'name': 'Kupwara'},
        {'code': '12', 'name': 'Poonch'},
        {'code': '13', 'name': 'Pulwama'},
        {'code': '14', 'name': 'Rajouri'},
        {'code': '15', 'name': 'Ramban'},
        {'code': '16', 'name': 'Reasi'},
        {'code': '17', 'name': 'Samba'},
        {'code': '18', 'name': 'Shopian'},
        {'code': '19', 'name': 'Srinagar'},
        {'code': '20', 'name': 'Udhampur'}
    ],
    '12': [  # Jharkhand
        {'code': '01', 'name': 'Bokaro'},
        {'code': '02', 'name': 'Chatra'},
        {'code': '03', 'name': 'Deoghar'},
        {'code': '04', 'name': 'Dhanbad'},
        {'code': '05', 'name': 'Dumka'},
        {'code': '06', 'name': 'East Singhbhum'},
        {'code': '07', 'name': 'Garhwa'},
        {'code': '08', 'name': 'Giridih'},
        {'code': '09', 'name': 'Godda'},
        {'code': '10', 'name': 'Gumla'},
        {'code': '11', 'name': 'Hazaribagh'},
        {'code': '12', 'name': 'Jamtara'},
        {'code': '13', 'name': 'Khunti'},
        {'code': '14', 'name': 'Koderma'},
        {'code': '15', 'name': 'Latehar'},
        {'code': '16', 'name': 'Lohardaga'},
        {'code': '17', 'name': 'Pakur'},
        {'code': '18', 'name': 'Palamu'},
        {'code': '19', 'name': 'Ramgarh'},
        {'code': '20', 'name': 'Ranchi'},
        {'code': '21', 'name': 'Sahibganj'},
        {'code': '22', 'name': 'Seraikela Kharsawan'},
        {'code': '23', 'name': 'Simdega'},
        {'code': '24', 'name': 'West Singhbhum'}
    ],
    '13': [  # Karnataka
        {'code': '01', 'name': 'Bagalkot'},
        {'code': '02', 'name': 'Ballari'},
        {'code': '03', 'name': 'Belagavi'},
        {'code': '04', 'name': 'Bengaluru Rural'},
        {'code': '05', 'name': 'Bengaluru Urban'},
        {'code': '06', 'name': 'Bidar'},
        {'code': '07', 'name': 'Chamarajanagar'},
        {'code': '08', 'name': 'Chikballapur'},
        {'code': '09', 'name': 'Chikkamagaluru'},
        {'code': '10', 'name': 'Chitradurga'},
        {'code': '11', 'name': 'Dakshina Kannada'},
        {'code': '12', 'name': 'Davangere'},
        {'code': '13', 'name': 'Dharwad'},
        {'code': '14', 'name': 'Gadag'},
        {'code': '15', 'name': 'Hassan'},
        {'code': '16', 'name': 'Haveri'},
        {'code': '17', 'name': 'Kalaburagi'},
        {'code': '18', 'name': 'Kodagu'},
        {'code': '19', 'name': 'Kolar'},
        {'code': '20', 'name': 'Koppal'},
        {'code': '21', 'name': 'Mandya'},
        {'code': '22', 'name': 'Mysuru'},
        {'code': '23', 'name': 'Raichur'},
        {'code': '24', 'name': 'Ramanagara'},
        {'code': '25', 'name': 'Shivamogga'},
        {'code': '26', 'name': 'Tumakuru'},
        {'code': '27', 'name': 'Udupi'},
        {'code': '28', 'name': 'Uttara Kannada'},
        {'code': '29', 'name': 'Vijayapura'},
        {'code': '30', 'name': 'Yadgir'}
    ],
    '14': [  # Kerala
        {'code': '01', 'name': 'Alappuzha'},
        {'code': '02', 'name': 'Ernakulam'},
        {'code': '03', 'name': 'Idukki'},
        {'code': '04', 'name': 'Kannur'},
        {'code': '05', 'name': 'Kasaragod'},
        {'code': '06', 'name': 'Kollam'},
        {'code': '07', 'name': 'Kottayam'},
        {'code': '08', 'name': 'Kozhikode'},
        {'code': '09', 'name': 'Malappuram'},
        {'code': '10', 'name': 'Palakkad'},
        {'code': '11', 'name': 'Pathanamthitta'},
        {'code': '12', 'name': 'Thiruvananthapuram'},
        {'code': '13', 'name': 'Thrissur'},
        {'code': '14', 'name': 'Wayanad'}
    ],
    '15': [  # Madhya Pradesh
        {'code': '01', 'name': 'Agar Malwa'},
        {'code': '02', 'name': 'Alirajpur'},
        {'code': '03', 'name': 'Anuppur'},
        {'code': '04', 'name': 'Ashoknagar'},
        {'code': '05', 'name': 'Balaghat'},
        {'code': '06', 'name': 'Barwani'},
        {'code': '07', 'name': 'Betul'},
        {'code': '08', 'name': 'Bhind'},
        {'code': '09', 'name': 'Bhopal'},
        {'code': '10', 'name': 'Burhanpur'},
        {'code': '11', 'name': 'Chhatarpur'},
        {'code': '12', 'name': 'Chhindwara'},
        {'code': '13', 'name': 'Damoh'},
        {'code': '14', 'name': 'Datia'},
        {'code': '15', 'name': 'Dewas'},
        {'code': '16', 'name': 'Dhar'},
        {'code': '17', 'name': 'Dindori'},
        {'code': '18', 'name': 'Guna'},
        {'code': '19', 'name': 'Gwalior'},
        {'code': '20', 'name': 'Harda'},
        {'code': '21', 'name': 'Hoshangabad'},
        {'code': '22', 'name': 'Indore'},
        {'code': '23', 'name': 'Jabalpur'},
        {'code': '24', 'name': 'Jhabua'},
        {'code': '25', 'name': 'Katni'},
        {'code': '26', 'name': 'Khandwa'},
        {'code': '27', 'name': 'Khargone'},
        {'code': '28', 'name': 'Mandla'},
        {'code': '29', 'name': 'Mandsaur'},
        {'code': '30', 'name': 'Morena'},
        {'code': '31', 'name': 'Narsinghpur'},
        {'code': '32', 'name': 'Neemuch'},
        {'code': '33', 'name': 'Panna'},
        {'code': '34', 'name': 'Raisen'},
        {'code': '35', 'name': 'Rajgarh'},
        {'code': '36', 'name': 'Ratlam'},
        {'code': '37', 'name': 'Rewa'},
        {'code': '38', 'name': 'Sagar'},
        {'code': '39', 'name': 'Satna'},
        {'code': '40', 'name': 'Sehore'},
        {'code': '41', 'name': 'Seoni'},
        {'code': '42', 'name': 'Shahdol'},
        {'code': '43', 'name': 'Shajapur'},
        {'code': '44', 'name': 'Sheopur'},
        {'code': '45', 'name': 'Shivpuri'},
        {'code': '46', 'name': 'Sidhi'},
        {'code': '47', 'name': 'Singrauli'},
        {'code': '48', 'name': 'Tikamgarh'},
        {'code': '49', 'name': 'Ujjain'},
        {'code': '50', 'name': 'Umaria'},
        {'code': '51', 'name': 'Vidisha'}
    ],
    '16': [  # Maharashtra
        {'code': '01', 'name': 'Ahmednagar'},
        {'code': '02', 'name': 'Akola'},
        {'code': '03', 'name': 'Amravati'},
        {'code': '04', 'name': 'Aurangabad'},
        {'code': '05', 'name': 'Beed'},
        {'code': '06', 'name': 'Bhandara'},
        {'code': '07', 'name': 'Buldhana'},
        {'code': '08', 'name': 'Chandrapur'},
        {'code': '09', 'name': 'Dhule'},
        {'code': '10', 'name': 'Gadchiroli'},
        {'code': '11', 'name': 'Gondia'},
        {'code': '12', 'name': 'Hingoli'},
        {'code': '13', 'name': 'Jalgaon'},
        {'code': '14', 'name': 'Jalna'},
        {'code': '15', 'name': 'Kolhapur'},
        {'code': '16', 'name': 'Latur'},
        {'code': '17', 'name': 'Mumbai City'},
        {'code': '18', 'name': 'Mumbai Suburban'},
        {'code': '19', 'name': 'Nagpur'},
        {'code': '20', 'name': 'Nanded'},
        {'code': '21', 'name': 'Nandurbar'},
        {'code': '22', 'name': 'Nashik'},
        {'code': '23', 'name': 'Osmanabad'},
        {'code': '24', 'name': 'Palghar'},
        {'code': '25', 'name': 'Parbhani'},
        {'code': '26', 'name': 'Pune'},
        {'code': '27', 'name': 'Raigad'},
        {'code': '28', 'name': 'Ratnagiri'},
        {'code': '29', 'name': 'Sangli'},
        {'code': '30', 'name': 'Satara'},
        {'code': '31', 'name': 'Sindhudurg'},
        {'code': '32', 'name': 'Solapur'},
        {'code': '33', 'name': 'Thane'},
        {'code': '34', 'name': 'Wardha'},
        {'code': '35', 'name': 'Washim'},
        {'code': '36', 'name': 'Yavatmal'}
    ],
    '17': [  # Manipur
        {'code': '01', 'name': 'Bishnupur'},
        {'code': '02', 'name': 'Chandel'},
        {'code': '03', 'name': 'Churachandpur'},
        {'code': '04', 'name': 'Imphal East'},
        {'code': '05', 'name': 'Imphal West'},
        {'code': '06', 'name': 'Jiribam'},
        {'code': '07', 'name': 'Kakching'},
        {'code': '08', 'name': 'Kamjong'},
        {'code': '09', 'name': 'Kangpokpi'},
        {'code': '10', 'name': 'Noney'},
        {'code': '11', 'name': 'Pherzawl'},
        {'code': '12', 'name': 'Senapati'},
        {'code': '13', 'name': 'Tamenglong'},
        {'code': '14', 'name': 'Tengnoupal'},
        {'code': '15', 'name': 'Thoubal'},
        {'code': '16', 'name': 'Ukhrul'}
    ],
    '18': [  # Meghalaya
        {'code': '01', 'name': 'East Garo Hills'},
        {'code': '02', 'name': 'East Jaintia Hills'},
        {'code': '03', 'name': 'East Khasi Hills'},
        {'code': '04', 'name': 'North Garo Hills'},
        {'code': '05', 'name': 'Ri Bhoi'},
        {'code': '06', 'name': 'South Garo Hills'},
        {'code': '07', 'name': 'South West Garo Hills'},
        {'code': '08', 'name': 'South West Khasi Hills'},
        {'code': '09', 'name': 'West Garo Hills'},
        {'code': '10', 'name': 'West Jaintia Hills'},
        {'code': '11', 'name': 'West Khasi Hills'},
        {'code': '12', 'name': 'Eastern West Khasi Hills'}
    ],
    '19': [  # Mizoram
        {'code': '01', 'name': 'Aizawl'},
        {'code': '02', 'name': 'Champhai'},
        {'code': '03', 'name': 'Hnahthial'},
        {'code': '04', 'name': 'Khawzawl'},
        {'code': '05', 'name': 'Kolasib'},
        {'code': '06', 'name': 'Lawngtlai'},
        {'code': '07', 'name': 'Lunglei'},
        {'code': '08', 'name': 'Mamit'},
        {'code': '09', 'name': 'Saiha'},
        {'code': '10', 'name': 'Saitual'},
        {'code': '11', 'name': 'Serchhip'}
    ],
    '20': [  # Nagaland
        {'code': '01', 'name': 'Dimapur'},
        {'code': '02', 'name': 'Kiphire'},
        {'code': '03', 'name': 'Kohima'},
        {'code': '04', 'name': 'Longleng'},
        {'code': '05', 'name': 'Mokokchung'},
        {'code': '06', 'name': 'Mon'},
        {'code': '07', 'name': 'Noklak'},
        {'code': '08', 'name': 'Peren'},
        {'code': '09', 'name': 'Phek'},
        {'code': '10', 'name': 'Tuensang'},
        {'code': '11', 'name': 'Wokha'},
        {'code': '12', 'name': 'Zunheboto'},
        {'code': '13', 'name': 'Chumukedima'},
        {'code': '14', 'name': 'Niuland'},
        {'code': '15', 'name': 'Shamator'},
        {'code': '16', 'name': 'Tseminyu'}
    ],
    '21': [  # Odisha
        {'code': '01', 'name': 'Angul'},
        {'code': '02', 'name': 'Balangir'},
        {'code': '03', 'name': 'Balasore'},
        {'code': '04', 'name': 'Bargarh'},
        {'code': '05', 'name': 'Bhadrak'},
        {'code': '06', 'name': 'Boudh'},
        {'code': '07', 'name': 'Cuttack'},
        {'code': '08', 'name': 'Deogarh'},
        {'code': '09', 'name': 'Dhenkanal'},
        {'code': '10', 'name': 'Gajapati'},
        {'code': '11', 'name': 'Ganjam'},
        {'code': '12', 'name': 'Jagatsinghpur'},
        {'code': '13', 'name': 'Jajpur'},
        {'code': '14', 'name': 'Jharsuguda'},
        {'code': '15', 'name': 'Kalahandi'},
        {'code': '16', 'name': 'Kandhamal'},
        {'code': '17', 'name': 'Kendrapara'},
        {'code': '18', 'name': 'Kendujhar'},
        {'code': '19', 'name': 'Khordha'},
        {'code': '20', 'name': 'Koraput'},
        {'code': '21', 'name': 'Malkangiri'},
        {'code': '22', 'name': 'Mayurbhanj'},
        {'code': '23', 'name': 'Nabarangpur'},
        {'code': '24', 'name': 'Nayagarh'},
        {'code': '25', 'name': 'Nuapada'},
        {'code': '26', 'name': 'Puri'},
        {'code': '27', 'name': 'Rayagada'},
        {'code': '28', 'name': 'Sambalpur'},
        {'code': '29', 'name': 'Sonepur'},
        {'code': '30', 'name': 'Sundargarh'}
    ],
    '22': [  # Punjab
        {'code': '01', 'name': 'Amritsar'},
        {'code': '02', 'name': 'Barnala'},
        {'code': '03', 'name': 'Bathinda'},
        {'code': '04', 'name': 'Faridkot'},
        {'code': '05', 'name': 'Fatehgarh Sahib'},
        {'code': '06', 'name': 'Fazilka'},
        {'code': '07', 'name': 'Ferozepur'},
        {'code': '08', 'name': 'Gurdaspur'},
        {'code': '09', 'name': 'Hoshiarpur'},
        {'code': '10', 'name': 'Jalandhar'},
        {'code': '11', 'name': 'Kapurthala'},
        {'code': '12', 'name': 'Ludhiana'},
        {'code': '13', 'name': 'Mansa'},
        {'code': '14', 'name': 'Moga'},
        {'code': '15', 'name': 'Muktsar'},
        {'code': '16', 'name': 'Nawanshahr'},
        {'code': '17', 'name': 'Pathankot'},
        {'code': '18', 'name': 'Patiala'},
        {'code': '19', 'name': 'Rupnagar'},
        {'code': '20', 'name': 'Sahibzada Ajit Singh Nagar'},
        {'code': '21', 'name': 'Sangrur'},
        {'code': '22', 'name': 'Tarn Taran'}
    ],
    '23': [  # Rajasthan
        {'code': '01', 'name': 'Ajmer'},
        {'code': '02', 'name': 'Alwar'},
        {'code': '03', 'name': 'Banswara'},
        {'code': '04', 'name': 'Baran'},
        {'code': '05', 'name': 'Barmer'},
        {'code': '06', 'name': 'Bharatpur'},
        {'code': '07', 'name': 'Bhilwara'},
        {'code': '08', 'name': 'Bikaner'},
        {'code': '09', 'name': 'Bundi'},
        {'code': '10', 'name': 'Chittorgarh'},
        {'code': '11', 'name': 'Churu'},
        {'code': '12', 'name': 'Dausa'},
        {'code': '13', 'name': 'Dholpur'},
        {'code': '14', 'name': 'Dungarpur'},
        {'code': '15', 'name': 'Hanumangarh'},
        {'code': '16', 'name': 'Jaipur'},
        {'code': '17', 'name': 'Jaisalmer'},
        {'code': '18', 'name': 'Jalore'},
        {'code': '19', 'name': 'Jhalawar'},
        {'code': '20', 'name': 'Jhunjhunu'},
        {'code': '21', 'name': 'Jodhpur'},
        {'code': '22', 'name': 'Karauli'},
        {'code': '23', 'name': 'Kota'},
        {'code': '24', 'name': 'Nagaur'},
        {'code': '25', 'name': 'Pali'},
        {'code': '26', 'name': 'Pratapgarh'},
        {'code': '27', 'name': 'Rajsamand'},
        {'code': '28', 'name': 'Sawai Madhopur'},
        {'code': '29', 'name': 'Sikar'},
        {'code': '30', 'name': 'Sirohi'},
        {'code': '31', 'name': 'Sri Ganganagar'},
        {'code': '32', 'name': 'Tonk'},
        {'code': '33', 'name': 'Udaipur'}
    ],
    '24': [  # Sikkim
        {'code': '01', 'name': 'East Sikkim'},
        {'code': '02', 'name': 'North Sikkim'},
        {'code': '03', 'name': 'South Sikkim'},
        {'code': '04', 'name': 'West Sikkim'},
        {'code': '05', 'name': 'Pakyong'},
        {'code': '06', 'name': 'Soreng'}
    ],
    '25': [  # Tamil Nadu
        {'code': '01', 'name': 'Ariyalur'},
        {'code': '02', 'name': 'Chengalpattu'},
        {'code': '03', 'name': 'Chennai'},
        {'code': '04', 'name': 'Coimbatore'},
        {'code': '05', 'name': 'Cuddalore'},
        {'code': '06', 'name': 'Dharmapuri'},
        {'code': '07', 'name': 'Dindigul'},
        {'code': '08', 'name': 'Erode'},
        {'code': '09', 'name': 'Kallakurichi'},
        {'code': '10', 'name': 'Kancheepuram'},
        {'code': '11', 'name': 'Kanyakumari'},
        {'code': '12', 'name': 'Karur'},
        {'code': '13', 'name': 'Krishnagiri'},
        {'code': '14', 'name': 'Madurai'},
        {'code': '15', 'name': 'Nagapattinam'},
        {'code': '16', 'name': 'Namakkal'},
        {'code': '17', 'name': 'Nilgiris'},
        {'code': '18', 'name': 'Perambalur'},
        {'code': '19', 'name': 'Pudukkottai'},
        {'code': '20', 'name': 'Ramanathapuram'},
        {'code': '21', 'name': 'Ranipet'},
        {'code': '22', 'name': 'Salem'},
        {'code': '23', 'name': 'Sivaganga'},
        {'code': '24', 'name': 'Tenkasi'},
        {'code': '25', 'name': 'Thanjavur'},
        {'code': '26', 'name': 'Theni'},
        {'code': '27', 'name': 'Thoothukudi'},
        {'code': '28', 'name': 'Tiruchirappalli'},
        {'code': '29', 'name': 'Tirunelveli'},
        {'code': '30', 'name': 'Tirupathur'},
        {'code': '31', 'name': 'Tiruppur'},
        {'code': '32', 'name': 'Tiruvallur'},
        {'code': '33', 'name': 'Tiruvannamalai'},
        {'code': '34', 'name': 'Tiruvarur'},
        {'code': '35', 'name': 'Vellore'},
        {'code': '36', 'name': 'Viluppuram'},
        {'code': '37', 'name': 'Virudhunagar'}
    ],
    '26': [  # Telangana
        {'code': '01', 'name': 'Adilabad'},
        {'code': '02', 'name': 'Bhadradri Kothagudem'},
        {'code': '03', 'name': 'Hanumakonda'},
        {'code': '04', 'name': 'Hyderabad'},
        {'code': '05', 'name': 'Jagtial'},
        {'code': '06', 'name': 'Jangaon'},
        {'code': '07', 'name': 'Jayashankar Bhupalpally'},
        {'code': '08', 'name': 'Jogulamba Gadwal'},
        {'code': '09', 'name': 'Kamareddy'},
        {'code': '10', 'name': 'Karimnagar'},
        {'code': '11', 'name': 'Khammam'},
        {'code': '12', 'name': 'Kumuram Bheem Asifabad'},
        {'code': '13', 'name': 'Mahabubabad'},
        {'code': '14', 'name': 'Mahabubnagar'},
        {'code': '15', 'name': 'Mancherial'},
        {'code': '16', 'name': 'Medak'},
        {'code': '17', 'name': 'Medchal Malkajgiri'},
        {'code': '18', 'name': 'Mulugu'},
        {'code': '19', 'name': 'Nagarkurnool'},
        {'code': '20', 'name': 'Nalgonda'},
        {'code': '21', 'name': 'Narayanpet'},
        {'code': '22', 'name': 'Nirmal'},
        {'code': '23', 'name': 'Nizamabad'},
        {'code': '24', 'name': 'Peddapalli'},
        {'code': '25', 'name': 'Rajanna Sircilla'},
        {'code': '26', 'name': 'Rangareddy'},
        {'code': '27', 'name': 'Sangareddy'},
        {'code': '28', 'name': 'Siddipet'},
        {'code': '29', 'name': 'Suryapet'},
        {'code': '30', 'name': 'Vikarabad'},
        {'code': '31', 'name': 'Wanaparthy'},
        {'code': '32', 'name': 'Warangal'},
        {'code': '33', 'name': 'Yadadri Bhuvanagiri'}
    ],
    '27': [  # Tripura
        {'code': '01', 'name': 'Dhalai'},
        {'code': '02', 'name': 'Gomati'},
        {'code': '03', 'name': 'Khowai'},
        {'code': '04', 'name': 'North Tripura'},
        {'code': '05', 'name': 'Sepahijala'},
        {'code': '06', 'name': 'South Tripura'},
        {'code': '07', 'name': 'Unakoti'},
        {'code': '08', 'name': 'West Tripura'}
    ],
    '28': [  # Uttar Pradesh
        {'code': '01', 'name': 'Agra'},
        {'code': '02', 'name': 'Aligarh'},
        {'code': '03', 'name': 'Allahabad'},
        {'code': '04', 'name': 'Ambedkar Nagar'},
        {'code': '05', 'name': 'Auraiya'},
        {'code': '06', 'name': 'Azamgarh'},
        {'code': '07', 'name': 'Baghpat'},
        {'code': '08', 'name': 'Bahraich'},
        {'code': '09', 'name': 'Ballia'},
        {'code': '10', 'name': 'Balrampur'},
        {'code': '11', 'name': 'Banda'},
        {'code': '12', 'name': 'Barabanki'},
        {'code': '13', 'name': 'Bareilly'},
        {'code': '14', 'name': 'Basti'},
        {'code': '15', 'name': 'Bijnor'},
        {'code': '16', 'name': 'Budaun'},
        {'code': '17', 'name': 'Bulandshahr'},
        {'code': '18', 'name': 'Chandauli'},
        {'code': '19', 'name': 'Chitrakoot'},
        {'code': '20', 'name': 'Deoria'},
        {'code': '21', 'name': 'Etah'},
        {'code': '22', 'name': 'Etawah'},
        {'code': '23', 'name': 'Faizabad'},
        {'code': '24', 'name': 'Farrukhabad'},
        {'code': '25', 'name': 'Fatehpur'},
        {'code': '26', 'name': 'Firozabad'},
        {'code': '27', 'name': 'Gautam Buddha Nagar'},
        {'code': '28', 'name': 'Ghaziabad'},
        {'code': '29', 'name': 'Ghazipur'},
        {'code': '30', 'name': 'Gonda'},
        {'code': '31', 'name': 'Gorakhpur'},
        {'code': '32', 'name': 'Hamirpur'},
        {'code': '33', 'name': 'Hapur'},
        {'code': '34', 'name': 'Hardoi'},
        {'code': '35', 'name': 'Hathras'},
        {'code': '36', 'name': 'Jalaun'},
        {'code': '37', 'name': 'Jaunpur'},
        {'code': '38', 'name': 'Jhansi'},
        {'code': '39', 'name': 'Kannauj'},
        {'code': '40', 'name': 'Kanpur Dehat'},
        {'code': '41', 'name': 'Kanpur Nagar'},
        {'code': '42', 'name': 'Kanshiram Nagar'},
        {'code': '43', 'name': 'Kaushambi'},
        {'code': '44', 'name': 'Kushinagar'},
        {'code': '45', 'name': 'Lakhimpur Kheri'},
        {'code': '46', 'name': 'Lalitpur'},
        {'code': '47', 'name': 'Lucknow'},
        {'code': '48', 'name': 'Maharajganj'},
        {'code': '49', 'name': 'Mahoba'},
        {'code': '50', 'name': 'Mainpuri'},
        {'code': '51', 'name': 'Mathura'},
        {'code': '52', 'name': 'Mau'},
        {'code': '53', 'name': 'Meerut'},
        {'code': '54', 'name': 'Mirzapur'},
        {'code': '55', 'name': 'Moradabad'},
        {'code': '56', 'name': 'Muzaffarnagar'},
        {'code': '57', 'name': 'Pilibhit'},
        {'code': '58', 'name': 'Pratapgarh'},
        {'code': '59', 'name': 'Rae Bareli'},
        {'code': '60', 'name': 'Rampur'},
        {'code': '61', 'name': 'Saharanpur'},
        {'code': '62', 'name': 'Sambhal'},
        {'code': '63', 'name': 'Sant Kabir Nagar'},
        {'code': '64', 'name': 'Shahjahanpur'},
        {'code': '65', 'name': 'Shamli'},
        {'code': '66', 'name': 'Shravasti'},
        {'code': '67', 'name': 'Siddharthnagar'},
        {'code': '68', 'name': 'Sitapur'},
        {'code': '69', 'name': 'Sonbhadra'},
        {'code': '70', 'name': 'Sultanpur'},
        {'code': '71', 'name': 'Unnao'},
        {'code': '72', 'name': 'Varanasi'},
        {'code': '73', 'name': 'Amethi'},
        {'code': '74', 'name': 'Hapur'},
        {'code': '75', 'name': 'Kasganj'}
    ],
    '29': [  # Uttarakhand
        {'code': '01', 'name': 'Almora'},
        {'code': '02', 'name': 'Bageshwar'},
        {'code': '03', 'name': 'Chamoli'},
        {'code': '04', 'name': 'Champawat'},
        {'code': '05', 'name': 'Dehradun'},
        {'code': '06', 'name': 'Haridwar'},
        {'code': '07', 'name': 'Nainital'},
        {'code': '08', 'name': 'Pauri Garhwal'},
        {'code': '09', 'name': 'Pithoragarh'},
        {'code': '10', 'name': 'Rudraprayag'},
        {'code': '11', 'name': 'Tehri Garhwal'},
        {'code': '12', 'name': 'Udham Singh Nagar'},
        {'code': '13', 'name': 'Uttarkashi'}
    ],
    '30': [  # West Bengal
        {'code': '01', 'name': 'Alipurduar'},
        {'code': '02', 'name': 'Bankura'},
        {'code': '03', 'name': 'Birbhum'},
        {'code': '04', 'name': 'Cooch Behar'},
        {'code': '05', 'name': 'Dakshin Dinajpur'},
        {'code': '06', 'name': 'Darjeeling'},
        {'code': '07', 'name': 'Hooghly'},
        {'code': '08', 'name': 'Howrah'},
        {'code': '09', 'name': 'Jalpaiguri'},
        {'code': '10', 'name': 'Jhargram'},
        {'code': '11', 'name': 'Kalimpong'},
        {'code': '12', 'name': 'Kolkata'},
        {'code': '13', 'name': 'Malda'},
        {'code': '14', 'name': 'Murshidabad'},
        {'code': '15', 'name': 'Nadia'},
        {'code': '16', 'name': 'North 24 Parganas'},
        {'code': '17', 'name': 'Paschim Bardhaman'},
        {'code': '18', 'name': 'Paschim Medinipur'},
        {'code': '19', 'name': 'Purba Bardhaman'},
        {'code': '20', 'name': 'Purba Medinipur'},
        {'code': '21', 'name': 'Purulia'},
        {'code': '22', 'name': 'South 24 Parganas'},
        {'code': '23', 'name': 'Uttar Dinajpur'}
    ],
    '31': [  # Puducherry
        {'code': '01', 'name': 'Karaikal'},
        {'code': '02', 'name': 'Mahe'},
        {'code': '03', 'name': 'Puducherry'},
        {'code': '04', 'name': 'Yanam'}
    ],
    '32': [  # Chandigarh
        {'code': '01', 'name': 'Chandigarh'}
    ],
    '33': [  # Dadra and Nagar Haveli and Daman and Diu (Merged UT)
        {'code': '01', 'name': 'Dadra and Nagar Haveli'},
        {'code': '02', 'name': 'Daman'},
        {'code': '03', 'name': 'Diu'}
    ],
    '34': [  # Ladakh
        {'code': '01', 'name': 'Leh'},
        {'code': '02', 'name': 'Kargil'}
    ],
    '35': [  # Lakshadweep
        {'code': '01', 'name': 'Lakshadweep'}
    ],
    '36': [  # Andaman and Nicobar Islands
        {'code': '01', 'name': 'Nicobar'},
        {'code': '02', 'name': 'North and Middle Andaman'},
        {'code': '03', 'name': 'South Andaman'}
    ]
}
